import type { NodeEstimate, PooledStatistic } from './types';

/**
 * Empirical-Bayes pooling across federated nodes.
 *
 * WHAT PROBLEM THIS SOLVES
 * ------------------------
 * Sixteen states each fit a model on their own data and publish the fitted
 * statistics. Two of them have watched the monsoon for six months; one joined
 * last month and has never seen July. Averaging the sixteen throws away the
 * fact that the estimates are not equally trustworthy. Taking each state's own
 * estimate at face value throws away fifteen states' worth of evidence for the
 * one that has almost none.
 *
 * The standard answer is a random-effects model. Each node's estimate is
 * treated as its own true value plus sampling noise, and the true values are
 * themselves treated as draws around a national mean with variance tau^2:
 *
 *     theta_i ~ N(mu, tau^2),   y_i ~ N(theta_i, se_i^2)
 *
 * tau^2 is estimated FROM THE NODES -- nobody sets it -- by the
 * DerSimonian-Laird method-of-moments estimator, and then each node's posterior
 * is a precision-weighted blend of what it measured and what everyone else did:
 *
 *     B_i = tau^2 / (tau^2 + se_i^2)        (how much of its own estimate it keeps)
 *     shrunk_i = B_i * y_i + (1 - B_i) * mu
 *
 * The two limits are the ones that matter. A node with a tight error bar in a
 * world where states genuinely differ (large tau^2) keeps its own number. A
 * node with no data at all (se = infinity, B = 0) receives the national mean
 * outright -- which is exactly what a state joining the grid should get on its
 * first day, and exactly what "shared predictive modelling across states" has
 * to mean if it is to mean anything.
 *
 * WHY IT IS GENERIC
 * -----------------
 * It pools `{value, se}` and nothing else. `scripts/build-federated.mts` runs
 * monthly seasonal multipliers and cadre vacancy rates through the identical
 * function. A pooling routine that only ever pooled one statistic would be that
 * statistic's helper wearing a general name.
 *
 * HONEST LIMITATION, STATED HERE AND ON THE PANEL
 * -----------------------------------------------
 * In this build all sixteen states are generated by ONE seeded simulator, so
 * genuine between-state heterogeneity is small by construction and the tau^2
 * this estimator recovers is largely an artefact of sampling. The mechanism is
 * real and the arithmetic is standard; the magnitude of the pooling weights is
 * a demonstration, not a finding about Indian states.
 */

/** Standard errors below this are treated as exactly zero information about spread. */
const MIN_SE = 1e-9;

/**
 * Pool one statistic across nodes and shrink each node back toward the pool.
 *
 * @param estimates one entry per node. `se: null` (or non-finite) means the node
 *   offered the statistic but has no data behind it; it contributes nothing to
 *   the pool and receives the pooled mean unchanged.
 * @param fallback what the pool means when NO node has evidence -- the neutral
 *   value of the statistic (1 for a seasonal multiplier). Six months of the year
 *   fall outside the shipped history window, and for those the country genuinely
 *   knows nothing; saying so with `tau^2 = 0` and every weight at zero is the
 *   honest answer. Omit it and the call throws instead, which is the right
 *   default for a statistic that is supposed to have data behind it.
 * @throws if no node carries usable information and no `fallback` was given -- a
 *   silent NaN here would propagate into a shipped forecast, and a pool with
 *   nothing in it is a bug at the call site, not a value.
 */
export function poolNodes(
  estimates: NodeEstimate[],
  label = 'statistic',
  fallback?: number,
): PooledStatistic {
  const informative = estimates.filter(
    (e) => Number.isFinite(e.value) && e.se !== null && Number.isFinite(e.se) && e.se > MIN_SE,
  ) as { node: string; value: number; se: number }[];
  const uninformativeNodes = estimates.length - informative.length;

  if (informative.length === 0) {
    if (fallback === undefined) {
      throw new Error(
        `poolNodes(${label}): none of ${estimates.length} nodes carried usable information`,
      );
    }
    return {
      mean: fallback,
      tauSquared: 0,
      q: 0,
      df: 0,
      iSquared: 0,
      nodes: 0,
      uninformativeNodes,
      shrunk: estimates.map((e) => ({ node: e.node, value: fallback, weight: 0 })),
    };
  }

  // --- fixed-effect pass: precision weights, and Cochran's Q from them -------
  let sumW = 0;
  let sumWY = 0;
  let sumW2 = 0;
  for (const e of informative) {
    const w = 1 / (e.se * e.se);
    sumW += w;
    sumWY += w * e.value;
    sumW2 += w * w;
  }
  const fixedMean = sumWY / sumW;

  let q = 0;
  for (const e of informative) {
    const w = 1 / (e.se * e.se);
    q += w * (e.value - fixedMean) ** 2;
  }
  const df = informative.length - 1;

  /*
   * DerSimonian-Laird. Q has expectation df under "all nodes share one true
   * value", so the excess of Q over df is what between-node variance has to
   * explain. C rescales that excess into variance units. Truncated at zero:
   * a negative variance estimate is the estimator telling us the nodes agree
   * more closely than their own error bars would predict, and the honest
   * reading of that is tau^2 = 0, not a negative number carried forward.
   */
  const c = sumW - sumW2 / sumW;
  const tauSquared = df > 0 && c > 0 ? Math.max(0, (q - df) / c) : 0;
  const iSquared = q > df && q > 0 ? (q - df) / q : 0;

  // --- random-effects pass --------------------------------------------------
  let sumWr = 0;
  let sumWrY = 0;
  for (const e of informative) {
    const w = 1 / (e.se * e.se + tauSquared);
    sumWr += w;
    sumWrY += w * e.value;
  }
  const mean = sumWrY / sumWr;

  const shrunk = estimates.map((e) => {
    const usable = Number.isFinite(e.value) && e.se !== null && Number.isFinite(e.se) && e.se > MIN_SE;
    if (!usable) return { node: e.node, value: mean, weight: 0 };
    const se2 = (e.se as number) ** 2;
    const b = tauSquared / (tauSquared + se2);
    return { node: e.node, value: b * e.value + (1 - b) * mean, weight: b };
  });

  return {
    mean,
    tauSquared,
    q,
    df,
    iSquared,
    nodes: informative.length,
    uninformativeNodes,
    shrunk,
  };
}

/**
 * Shrink ONE node's estimate toward a prior that was pooled without it.
 *
 * Separate from `poolNodes` on purpose. `poolNodes` answers "what does the
 * country believe"; this answers "what should a state believe, given what the
 * REST of the country believes" -- and keeping the two apart is what makes a
 * leave-one-state-out evaluation possible. If a state's own data were inside
 * the prior it is being pulled toward, every measured improvement would be
 * partly that state predicting itself.
 */
export function shrinkToPrior(
  value: number,
  se: number | null,
  prior: { mean: number; tauSquared: number },
): { value: number; weight: number } {
  const usable = Number.isFinite(value) && se !== null && Number.isFinite(se) && se > MIN_SE;
  if (!usable) return { value: prior.mean, weight: 0 };
  const b = prior.tauSquared / (prior.tauSquared + (se as number) ** 2);
  return { value: b * value + (1 - b) * prior.mean, weight: b };
}
