'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import IndiaMap, { type MapDistrict, type MapMetric } from './IndiaMap';
import { Kpi, Stat, Th } from './ui/primitives';
import type { NationalSnapshot } from '@/lib/snapshot-types';
import {
  inr,
  count,
  compactCount,
  days,
  pct,
  SEVERITY_CLASS,
  VED_LABEL,
  type Severity,
} from '@/lib/format';

const METRICS: { key: MapMetric; label: string }[] = [
  { key: 'risk', label: 'Risk' },
  { key: 'critical', label: 'Critical' },
  { key: 'zero', label: 'Zero stock' },
  { key: 'waste', label: 'Expiring' },
];

export default function NationalConsole({ snapshot }: { snapshot: NationalSnapshot }) {
  const [metric, setMetric] = useState<MapMetric>('risk');
  const [selected, setSelected] = useState<string | null>(null);

  const mapDistricts: MapDistrict[] = useMemo(
    () =>
      snapshot.districts.map((d) => ({
        code: d.districtCode,
        name: d.districtName,
        stateName: d.stateName,
        lat: d.lat,
        lon: d.lon,
        meanRiskScore: d.meanRiskScore,
        criticalPositions: d.criticalPositions,
        facilities: d.facilities,
        projectedWasteInr: d.projectedWasteInr,
        zeroStockShare: d.zeroStockShare,
        population: d.population,
      })),
    [snapshot.districts],
  );

  /**
   * States ranked by absence among filled posts.
   *
   * Absence, not vacancy, because the two gaps have different owners: an empty
   * post is a state cadre and recruitment problem measured in years, while a
   * filled post that is not attended is a district supervision problem
   * measured in weeks. Ranking by the second surfaces the one a reader of this
   * page can actually do something about before the next monsoon.
   */
  const workforceStates = useMemo(
    () => [...snapshot.states].sort((a, b) => b.absenteeismRate - a.absenteeismRate).slice(0, 12),
    [snapshot.states],
  );

  const worstDistricts = useMemo(
    () => [...snapshot.districts].sort((a, b) => b.meanRiskScore - a.meanRiskScore).slice(0, 12),
    [snapshot.districts],
  );

  const visibleAlerts = useMemo(() => {
    const list = selected
      ? snapshot.alerts.filter((a) => a.districtCode === selected)
      : snapshot.alerts;
    return list.slice(0, 40);
  }, [snapshot.alerts, selected]);

  const selectedDistrict = selected
    ? snapshot.districts.find((d) => d.districtCode === selected)
    : null;

  const t = snapshot.totals;

  return (
    <div className="min-h-screen">
      {/* ---------------- header ---------------- */}
      <header className="sticky top-0 z-20 border-b border-ink-700 bg-ink-950/95 backdrop-blur">
        <div className="mx-auto max-w-[1600px] px-4 py-3 flex items-center gap-4 flex-wrap">
          <div className="flex items-center gap-2.5">
            <div className="w-7 h-7 rounded bg-brand/15 border border-brand/40 grid place-items-center">
              <span className="text-brand text-sm font-bold">A</span>
            </div>
            <div>
              <h1 className="text-sm font-semibold tracking-tight leading-none">Aarogya Grid</h1>
              <p className="text-[10px] text-mist-400 leading-none mt-1">
                Medicines, beds and health workforce · national
              </p>
            </div>
          </div>

          <div className="h-8 w-px bg-ink-700 hidden sm:block" />

          <div className="text-[11px] text-mist-400">
            <span className="text-mist-200 tnum">{snapshot.asOf}</span> · position as of
          </div>

          <div className="flex-1" />

          <Link
            href="/capture"
            className="text-[11px] px-3 py-1.5 rounded border border-brand/40 text-brand hover:bg-brand/10 transition-colors"
          >
            Field capture →
          </Link>

          <span
            className="text-[10px] px-2 py-1 rounded border border-sev-moderate/30 bg-sev-moderate/10 text-sev-moderate"
            title="Facility stock, bed occupancy and staff attendance figures are generated by a seeded simulator parameterised from IPHS norms and published seasonality -- NOT fitted to observed data. Districts, coordinates, tier structure, bed norms, the staffing establishment and the drug catalogue are real. District rankings therefore reflect a synthetic reliability parameter, not real performance."
          >
            SIMULATED FACILITY DATA
          </span>
        </div>
      </header>

      <main className="mx-auto max-w-[1600px] px-4 py-4 space-y-4">
        {/* ---------------- KPI strip ---------------- */}
        <section className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
          <Kpi label="Facilities tracked" value={count(t.facilities)} sub={`${count(t.districts)} districts · ${count(t.states)} states`} />
          <Kpi label="Stock positions" value={compactCount(t.trackedPositions)} sub="facility × drug pairs" />
          <Kpi
            label="Critical positions"
            value={count(t.criticalPositions)}
            sub={`${count(t.zeroStockPositions)} at zero stock`}
            tone="critical"
          />
          <Kpi label="Population covered" value={compactCount(t.populationCovered)} sub="modelled catchment" />
          <Kpi label="Stock heading to expiry" value={inr(t.projectedWasteInr)} sub="next 90 days" tone="high" />
          {/* Deliberately NOT the objective value. The optimiser's net benefit is
              dominated by a shortage penalty -- a policy multiplier, not money --
              so reporting it as a rupee figure would overstate the case by an
              order of magnitude. The honest headline is the physical quantity:
              units of unmet demand averted. The cash consequence is shown in full,
              including its negative sign, in the plan economics panel below. */}
          <Kpi
            label="Shortfall averted"
            value={compactCount(t.shortfallAverted)}
            sub={`units · ${count(t.transfers)} dispatches`}
            tone="good"
          />
        </section>

        {/* ---------------- plan economics ----------------
            This panel exists because the optimiser's objective value is NOT a
            cash figure, and presenting it as one would be the single most
            misleading thing on the page. Redistribution is cash-negative: it
            spends more on transport than it recovers in averted waste. It is
            justified by the shortfall it prevents, valued at a shortage penalty
            that is a POLICY parameter, not a market price. So we show the cash
            arithmetic in full, including its sign, and state the break-even
            explicitly -- the reader can then disagree with the valuation rather
            than being quietly sold it. */}
        <section className="panel">
          <div className="panel-head">
            <span>Plan economics · national</span>
            <span className="text-mist-500 normal-case tracking-normal">
              {count(t.transfers)} dispatches across {count(t.districts)} districts
            </span>
          </div>
          <div className="p-3 grid grid-cols-1 lg:grid-cols-[auto_1fr] gap-x-8 gap-y-3">
            <table className="text-xs">
              <tbody className="divide-y divide-ink-800">
                <tr>
                  <td className="py-1.5 pr-8 text-mist-400">Waste averted</td>
                  <td className="py-1.5 text-right tnum text-sev-low">+ {inr(t.wasteAvertedInr)}</td>
                </tr>
                <tr>
                  <td className="py-1.5 pr-8 text-mist-400">Transport cost</td>
                  <td className="py-1.5 text-right tnum text-sev-critical">− {inr(t.transportCostInr)}</td>
                </tr>
                <tr>
                  <td className="py-1.5 pr-8 text-mist-200">Net cash position</td>
                  <td className="py-1.5 text-right tnum text-sev-critical font-semibold">
                    − {inr(t.transportCostInr - t.wasteAvertedInr)}
                  </td>
                </tr>
                <tr>
                  <td className="py-1.5 pr-8 text-mist-200">Shortfall averted</td>
                  <td className="py-1.5 text-right tnum text-sev-low font-semibold">
                    {count(t.shortfallAverted)} units
                  </td>
                </tr>
              </tbody>
            </table>
            <p className="text-[11px] leading-relaxed text-mist-400 max-w-[62ch]">
              Redistribution does not pay for itself in cash — it spends more moving stock than it
              recovers in averted expiry. It is justified by the shortfall it prevents. The plan
              breaks even when one unit of averted unmet demand is valued at{' '}
              <span className="tnum text-mist-100">
                ₹{((t.transportCostInr - t.wasteAvertedInr) / Math.max(1, t.shortfallAverted)).toFixed(2)}
              </span>
              . Whether a dose of a <span className="text-sev-critical">Vital</span> medicine reaching
              a patient is worth that is a policy judgement, not an engineering one, so the shortage
              penalty is an explicit parameter rather than something folded into a headline figure.
            </p>
          </div>
        </section>

        {/* ---------------- beds and workforce ----------------
            The challenge this system answers names three resources -- medicine
            stocks, bed availability and personnel attendance -- and they are on
            one page rather than three tabs for a reason that is structural, not
            presentational. Occupancy drives consumption; attendance decides
            whether the consumption was ever written down. Split across tabs,
            those two facts become somebody else's problem. Kept together, the
            stock board above carries its own error bar. */}
        <section className="panel">
          <div className="panel-head">
            <span>Beds and health workforce · national</span>
            <span className="text-mist-500 normal-case tracking-normal">
              IPHS establishment vs what exists on {snapshot.asOf}
            </span>
          </div>

          <div className="p-3 space-y-3">
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
              <Kpi
                label="Functional beds"
                value={compactCount(t.functionalBeds)}
                sub={`of ${compactCount(t.sanctionedBeds)} sanctioned · ${compactCount(t.staffedBeds)} staffed today`}
              />
              <Kpi
                label="Bed occupancy"
                value={pct(t.bedOccupancyRate, 0)}
                sub={`${count(t.facilitiesAtCapacity)} facilities at capacity`}
                tone={t.bedOccupancyRate >= 0.85 ? 'critical' : undefined}
              />
              {/* The censored quantity. Named as what it is, not as "utilisation". */}
              <Kpi
                label="Demand that found no bed"
                value={compactCount(t.unmetBedDays)}
                sub="patient-days · in no occupancy return anywhere"
                tone="critical"
              />
              <Kpi
                label="Staff present today"
                value={compactCount(t.staffPresent)}
                sub={`of ${compactCount(t.staffSanctioned)} sanctioned posts`}
                tone={t.staffPresent / Math.max(1, t.staffSanctioned) < 0.6 ? 'critical' : undefined}
              />
              <Kpi
                label="Vacancy · absence"
                value={`${pct(t.vacancyRate, 0)} · ${pct(t.absenteeismRate, 0)}`}
                sub="posts unfilled · filled posts not attending"
                tone="high"
              />
              <Kpi
                label="Specialist posts filled"
                value={`${compactCount(t.specialistInPosition)} of ${compactCount(t.specialistSanctioned)}`}
                sub="surgeon · physician · O&G · paediatrician"
                tone="critical"
              />
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-[1fr_1fr] gap-4">
              {/*
               * Two sentences that only a system holding all three resources
               * can write. Everything in them is arithmetic over figures
               * already on this page -- the value is that they are next to each
               * other.
               */}
              <p className="text-[11px] leading-relaxed text-mist-400 max-w-[70ch]">
                <span className="text-mist-200 font-semibold">
                  Why the stock board above needs an error bar.{' '}
                </span>
                <span className="tnum text-mist-100">
                  {count(t.facilitiesWithoutPharmacist)}
                </span>{' '}
                stock-holding facilities have no pharmacist in position and{' '}
                <span className="tnum text-mist-100">{count(t.subCentresWithoutAnm)}</span>{' '}
                sub-centres have no ANM — these are the posts that keep the stock register. Across
                the network that leaves{' '}
                <span className="tnum text-sev-high">
                  {count(t.facilitiesUnverifiedReporting)}
                </span>{' '}
                facilities serving{' '}
                <span className="tnum text-mist-100">
                  {compactCount(t.populationUnderUnverifiedReporting)}
                </span>{' '}
                people whose reported stock nobody was in position to count. Those quantities are
                still shown, in the same table as every other — flagged, at facility level, on the
                district console.
                <br />
                <br />
                <span className="text-mist-200 font-semibold">And why occupancy is on it. </span>
                Ward occupancy runs on the same monsoon and enteric calendar as drug demand, from
                one seasonality model rather than two. A ward filling in September is the same wave
                that empties the antimalarial shelf, so consumption is scaled by occupancy against
                the tier baseline instead of being forecast as if the ward were empty.
              </p>

              {/*
               * State-level workforce table. The challenge asks for shared
               * predictive modelling across states; the first thing that has to
               * be comparable across states is the establishment itself, and
               * these are the same three levels every facility row carries,
               * summed. Ranked by absence rather than vacancy because vacancy
               * belongs to the state cadre authority and absence belongs to the
               * district -- and only one of the two is actionable this quarter.
               */}
              <div className="overflow-x-auto">
                <table className="w-full text-xs">
                  <thead>
                    <tr className="text-[10px] uppercase tracking-wider text-mist-400 border-b border-ink-700">
                      <Th className="text-left">State</Th>
                      <Th className="text-right">Beds</Th>
                      <Th className="text-right">Occupancy</Th>
                      <Th className="text-right">Present / sanctioned</Th>
                      <Th className="text-right">Vacancy</Th>
                      <Th className="text-right">Absent</Th>
                      <Th className="text-right">No pharmacist</Th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-ink-800">
                    {workforceStates.map((st) => (
                      <tr key={st.stateCode} className="row-hover transition-colors">
                        <td className="py-1.5 text-mist-100">{st.stateName}</td>
                        <td className="py-1.5 text-right tnum text-mist-300">
                          {count(st.functionalBeds)}
                        </td>
                        <td className="py-1.5 text-right tnum text-mist-200">
                          {pct(st.bedOccupancyRate, 0)}
                        </td>
                        <td className="py-1.5 text-right tnum text-mist-300">
                          {count(st.staffPresent)}
                          <span className="text-mist-500"> / {count(st.staffSanctioned)}</span>
                        </td>
                        <td className="py-1.5 text-right tnum text-sev-high">
                          {pct(st.vacancyRate, 0)}
                        </td>
                        <td className="py-1.5 text-right tnum text-sev-moderate">
                          {pct(st.absenteeismRate, 0)}
                        </td>
                        <td className="py-1.5 text-right tnum text-mist-300">
                          {count(st.facilitiesWithoutPharmacist)}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </section>

        {/* ---------------- map + side ---------------- */}
        <section className="grid grid-cols-1 lg:grid-cols-[1.35fr_1fr] gap-4">
          <div className="panel overflow-hidden">
            <div className="panel-head">
              <span>National view</span>
              <div className="flex gap-1">
                {METRICS.map((m) => (
                  <button
                    key={m.key}
                    onClick={() => setMetric(m.key)}
                    className={
                      'px-2 py-1 rounded text-[10px] border transition-colors ' +
                      (metric === m.key
                        ? 'border-brand/50 bg-brand/10 text-brand'
                        : 'border-ink-600 text-mist-400 hover:text-mist-200 hover:border-ink-500')
                    }
                  >
                    {m.label}
                  </button>
                ))}
              </div>
            </div>
            <div className="p-2">
              <IndiaMap
                districts={mapDistricts}
                metric={metric}
                selectedDistrict={selected}
                onSelectDistrict={(code) => setSelected(code === selected ? null : code)}
              />
            </div>
          </div>

          <div className="space-y-4">
            {/* selected district card */}
            {selectedDistrict && (
              <div className="panel">
                <div className="panel-head">
                  <span>{selectedDistrict.districtName}, {selectedDistrict.stateName}</span>
                  <button
                    onClick={() => setSelected(null)}
                    className="text-mist-400 hover:text-mist-100 text-[10px]"
                  >
                    clear
                  </button>
                </div>
                <div className="p-3 grid grid-cols-2 gap-x-4 gap-y-2 text-xs">
                  <Stat label="Facilities" value={count(selectedDistrict.facilities)} />
                  <Stat label="Positions" value={count(selectedDistrict.trackedPositions)} />
                  <Stat label="Critical" value={count(selectedDistrict.criticalPositions)} tone="critical" />
                  <Stat label="Zero stock" value={pct(selectedDistrict.zeroStockShare)} />
                  <Stat label="Mean risk" value={selectedDistrict.meanRiskScore.toFixed(1)} />
                  <Stat label="Expiring" value={inr(selectedDistrict.projectedWasteInr)} />
                  <Stat
                    label="Supply reliability"
                    value={pct(selectedDistrict.reliability, 0)}
                    hint="Modelled: how reliably consignments arrive complete and on time."
                  />
                  <Stat
                    label="Demand-driven"
                    value={pct(selectedDistrict.pullFraction, 0)}
                    hint="How far allocation follows real consumption rather than tier norms. Low values mean push allocation, which starves large facilities and overstocks small ones."
                  />
                  {/*
                   * Beds and people on the same card as stock, so a reader who
                   * clicks a district gets the caveat with the figure rather
                   * than one screen later.
                   */}
                  <Stat
                    label="Bed occupancy"
                    value={pct(selectedDistrict.resources.bedOccupancyRate, 0)}
                    tone={selectedDistrict.resources.bedOccupancyRate >= 0.9 ? 'critical' : undefined}
                    hint={`${selectedDistrict.resources.occupiedBeds} of ${selectedDistrict.resources.functionalBeds} functional beds, ${selectedDistrict.resources.sanctionedBeds} sanctioned. ${selectedDistrict.resources.unmetBedDays} patient-days of admission demand found no bed.`}
                  />
                  <Stat
                    label="Staff present"
                    value={pct(selectedDistrict.resources.effectiveAvailability, 0)}
                    tone={selectedDistrict.resources.effectiveAvailability < 0.6 ? 'critical' : undefined}
                    hint={`${selectedDistrict.resources.staffPresent} present of ${selectedDistrict.resources.staffSanctioned} sanctioned posts. Vacancy ${(selectedDistrict.resources.vacancyRate * 100).toFixed(0)}%, absence among filled posts ${(selectedDistrict.resources.absenteeismRate * 100).toFixed(0)}%.`}
                  />
                  <Stat
                    label="Facilities w/o pharmacist"
                    value={count(selectedDistrict.resources.facilitiesWithoutPharmacist)}
                    tone={selectedDistrict.resources.facilitiesWithoutPharmacist > 0 ? 'critical' : undefined}
                    hint="Stock-holding facilities with nobody in position to keep the register. Their reported quantities are estimates, not counts."
                  />
                  <Stat
                    label="Stock report trust"
                    value={pct(selectedDistrict.resources.meanReportTrust, 0)}
                    hint="Population-weighted mean confidence in this district's stock reports, driven by whether the custodian post is filled and attended."
                  />
                </div>
                <div className="px-3 pb-3">
                  <Link
                    href={`/district/${selectedDistrict.districtCode}`}
                    className="block text-center text-[11px] py-1.5 rounded border border-brand/40 text-brand hover:bg-brand/10 transition-colors"
                  >
                    Open district console →
                  </Link>
                </div>
              </div>
            )}

            {/* worst districts */}
            <div className="panel">
              <div className="panel-head">
                <span>Highest-risk districts</span>
                <span className="text-mist-500 normal-case tracking-normal">
                  population-weighted
                </span>
              </div>
              <div className="divide-y divide-ink-800">
                {worstDistricts.map((d, i) => (
                  <button
                    key={d.districtCode}
                    onClick={() => setSelected(d.districtCode)}
                    className="row-hover w-full text-left px-3 py-2 flex items-center gap-3 transition-colors"
                  >
                    <span className="tnum text-[10px] text-mist-500 w-5">{i + 1}</span>
                    <span className="flex-1 min-w-0">
                      <span className="block text-xs text-mist-100 truncate">{d.districtName}</span>
                      <span className="block text-[10px] text-mist-400 truncate">{d.stateName}</span>
                    </span>
                    <span className="text-right">
                      <span className="block tnum text-xs text-mist-100">{d.meanRiskScore.toFixed(1)}</span>
                      <span className="block text-[10px] text-mist-400 tnum">
                        {count(d.criticalPositions)} crit
                      </span>
                    </span>
                  </button>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* ---------------- alerts ---------------- */}
        <section className="panel">
          <div className="panel-head">
            <span>
              Priority stock alerts
              {selected && selectedDistrict ? ` · ${selectedDistrict.districtName}` : ' · national'}
            </span>
            <span className="text-mist-500 normal-case tracking-normal">
              ranked by risk score · {count(visibleAlerts.length)} shown
            </span>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-xs">
              <thead>
                <tr className="text-[10px] uppercase tracking-wider text-mist-400 border-b border-ink-700">
                  <Th className="text-left pl-3">Facility</Th>
                  <Th className="text-left">District</Th>
                  <Th className="text-left">Drug</Th>
                  <Th>VED</Th>
                  <Th className="text-right">On hand</Th>
                  <Th className="text-right">Cover</Th>
                  <Th className="text-right">Lead</Th>
                  <Th className="text-right">P(out)</Th>
                  <Th className="text-right">Shortfall</Th>
                  <Th className="text-right pr-3">Risk</Th>
                </tr>
              </thead>
              <tbody className="divide-y divide-ink-800">
                {visibleAlerts.map((a, i) => (
                  <tr key={a.facilityId + a.drugId + i} className="row-hover transition-colors">
                    <td className="pl-3 py-1.5">
                      <span className="text-mist-100">{a.facilityName}</span>
                    </td>
                    <td className="text-mist-400">
                      {a.districtName}
                      <span className="text-mist-500"> · {a.stateName}</span>
                    </td>
                    <td className="text-mist-200">
                      {a.drugName}
                      <span className="text-mist-500"> {a.drugStrength}</span>
                    </td>
                    <td className="text-center">
                      <span
                        className={
                          'text-[10px] px-1.5 py-0.5 rounded border ' +
                          (a.ved === 'V'
                            ? 'border-sev-critical/40 text-sev-critical bg-sev-critical/10'
                            : a.ved === 'E'
                              ? 'border-sev-high/30 text-sev-high bg-sev-high/10'
                              : 'border-ink-600 text-mist-400')
                        }
                        title={VED_LABEL[a.ved]}
                      >
                        {a.ved}
                      </span>
                    </td>
                    <td className="text-right tnum">
                      {a.onHand === 0 ? (
                        <span className="text-sev-critical font-semibold">0</span>
                      ) : (
                        <span className="text-mist-200">{count(a.onHand)}</span>
                      )}
                      <span className="text-mist-500 text-[10px]"> {a.unit}</span>
                    </td>
                    <td className="text-right tnum text-mist-300">{days(a.daysOfCover)}</td>
                    <td className="text-right tnum text-mist-400">{a.leadTimeDays}d</td>
                    <td className="text-right tnum text-mist-200">
                      {(a.stockoutProbability * 100).toFixed(0)}%
                    </td>
                    <td className="text-right tnum text-mist-300">
                      {count(a.expectedShortfallUnits)}
                    </td>
                    <td className="text-right pr-3 py-1.5">
                      <span
                        className={
                          'tnum text-[11px] px-1.5 py-0.5 rounded border ' +
                          SEVERITY_CLASS[a.severity as Severity]
                        }
                      >
                        {a.riskScore}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          {visibleAlerts.length === 0 && (
            <p className="p-4 text-xs text-mist-400">No critical alerts in this district.</p>
          )}
        </section>

        {/* ---------------- provenance ---------------- */}
        <footer className="panel p-4 text-[11px] text-mist-400 leading-relaxed">
          <p className="text-mist-200 font-semibold mb-2 text-xs">What is real here, and what is not</p>
          <div className="grid md:grid-cols-2 gap-4">
            <div>
              <p className="text-sev-low mb-1">Real</p>
              <ul className="space-y-0.5 list-disc list-inside">
                <li>Districts, state LGD/Census codes, and coordinates</li>
                <li>IPHS facility tiers, catchment norms and bed strength</li>
                <li>IPHS staffing establishment by tier and cadre</li>
                <li>Drug catalogue, VED classification, cold-chain flags</li>
                <li>Every model, forecast and optimisation in the system</li>
              </ul>
            </div>
            <div>
              <p className="text-sev-moderate mb-1">Simulated</p>
              <ul className="space-y-0.5 list-disc list-inside">
                <li>Individual facilities, their names and catchments</li>
                <li>Stock positions, batches and consumption ledgers</li>
                <li>Bed occupancy, staff vacancy and daily attendance</li>
                <li>District supply reliability and allocation behaviour</li>
              </ul>
            </div>
          </div>
          <p className="mt-3 pt-3 border-t border-ink-800">
            Real PHC inventory data is not public. The facility layer is generated by a seeded
            simulator, parameterised from IPHS norms and published epidemiological seasonality but{' '}
            <span className="text-mist-300">not fitted to observed consumption</span> -- so district
            rankings reflect a synthetic reliability parameter, not real performance. Connecting a
            live DVDMS / e-Aushadhi extract replaces the simulator and changes nothing downstream.
            The same applies to beds and workforce, which would come from HMIS occupancy returns,
            the state HRMIS establishment and facility attendance respectively. One caveat specific
            to that layer:{' '}
            <span className="text-mist-300">
              the workforce map and the stock map are correlated by construction
            </span>{' '}
            — remoteness is derived from the same synthetic district reliability parameter that
            drives supply, so the fact that badly-supplied districts are also badly-staffed here is
            an assumption of the model, not a finding from it. Snapshot of{' '}
            <span className="tnum text-mist-300">{count(t.trackedPositions)}</span> stock positions
            computed in <span className="tnum text-mist-300">{snapshot.buildSeconds}s</span>.
          </p>
        </footer>
      </main>
    </div>
  );
}
