'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import IndiaMap, { type MapDistrict, type MapMetric } from './IndiaMap';
import { Kpi, Stat, Th } from './ui/primitives';
import type { NationalSnapshot } from '@/lib/snapshot-types';
import {
  inr,
  count,
  compactCount,
  days,
  pct,
  SEVERITY_CLASS,
  VED_LABEL,
  type Severity,
} from '@/lib/format';

const METRICS: { key: MapMetric; label: string }[] = [
  { key: 'risk', label: 'Risk' },
  { key: 'critical', label: 'Critical' },
  { key: 'zero', label: 'Zero stock' },
  { key: 'waste', label: 'Expiring' },
];

export default function NationalConsole({ snapshot }: { snapshot: NationalSnapshot }) {
  const [metric, setMetric] = useState<MapMetric>('risk');
  const [selected, setSelected] = useState<string | null>(null);

  const mapDistricts: MapDistrict[] = useMemo(
    () =>
      snapshot.districts.map((d) => ({
        code: d.districtCode,
        name: d.districtName,
        stateName: d.stateName,
        lat: d.lat,
        lon: d.lon,
        meanRiskScore: d.meanRiskScore,
        criticalPositions: d.criticalPositions,
        facilities: d.facilities,
        projectedWasteInr: d.projectedWasteInr,
        zeroStockShare: d.zeroStockShare,
        population: d.population,
      })),
    [snapshot.districts],
  );

  const stateRisk = useMemo(() => {
    const m: Record<string, number> = {};
    for (const s of snapshot.states) m[s.stateCode] = s.meanRiskScore;
    return m;
  }, [snapshot.states]);

  const worstDistricts = useMemo(
    () => [...snapshot.districts].sort((a, b) => b.meanRiskScore - a.meanRiskScore).slice(0, 12),
    [snapshot.districts],
  );

  const visibleAlerts = useMemo(() => {
    const list = selected
      ? snapshot.alerts.filter((a) => a.districtCode === selected)
      : snapshot.alerts;
    return list.slice(0, 40);
  }, [snapshot.alerts, selected]);

  const selectedDistrict = selected
    ? snapshot.districts.find((d) => d.districtCode === selected)
    : null;

  const t = snapshot.totals;

  return (
    <div className="min-h-screen">
      {/* ---------------- header ---------------- */}
      <header className="sticky top-0 z-20 border-b border-ink-700 bg-ink-950/95 backdrop-blur">
        <div className="mx-auto max-w-[1600px] px-4 py-3 flex items-center gap-4 flex-wrap">
          <div className="flex items-center gap-2.5">
            <div className="w-7 h-7 rounded bg-brand/15 border border-brand/40 grid place-items-center">
              <span className="text-brand text-sm font-bold">A</span>
            </div>
            <div>
              <h1 className="text-sm font-semibold tracking-tight leading-none">Aarogya Grid</h1>
              <p className="text-[10px] text-mist-400 leading-none mt-1">
                National medicine supply intelligence
              </p>
            </div>
          </div>

          <div className="h-8 w-px bg-ink-700 hidden sm:block" />

          <div className="text-[11px] text-mist-400">
            <span className="text-mist-200 tnum">{snapshot.asOf}</span> · position as of
          </div>

          <div className="flex-1" />

          <Link
            href="/capture"
            className="text-[11px] px-3 py-1.5 rounded border border-brand/40 text-brand hover:bg-brand/10 transition-colors"
          >
            Field capture →
          </Link>

          <span
            className="text-[10px] px-2 py-1 rounded border border-sev-moderate/30 bg-sev-moderate/10 text-sev-moderate"
            title="Facility stock and consumption figures are generated by a calibrated simulator. Districts, coordinates, tier structure and the drug catalogue are real."
          >
            SIMULATED STOCK DATA
          </span>
        </div>
      </header>

      <main className="mx-auto max-w-[1600px] px-4 py-4 space-y-4">
        {/* ---------------- KPI strip ---------------- */}
        <section className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
          <Kpi label="Facilities tracked" value={count(t.facilities)} sub={`${count(t.districts)} districts · ${count(t.states)} states`} />
          <Kpi label="Stock positions" value={compactCount(t.trackedPositions)} sub="facility × drug pairs" />
          <Kpi
            label="Critical positions"
            value={count(t.criticalPositions)}
            sub={`${count(t.zeroStockPositions)} at zero stock`}
            tone="critical"
          />
          <Kpi label="Population covered" value={compactCount(t.populationCovered)} sub="modelled catchment" />
          <Kpi label="Stock heading to expiry" value={inr(t.projectedWasteInr)} sub="next 90 days" tone="high" />
          <Kpi
            label="Redistribution value"
            value={inr(t.netBenefitInr)}
            sub={`${count(t.transfers)} transfers found`}
            tone="good"
          />
        </section>

        {/* ---------------- map + side ---------------- */}
        <section className="grid grid-cols-1 lg:grid-cols-[1.35fr_1fr] gap-4">
          <div className="panel overflow-hidden">
            <div className="panel-head">
              <span>National view</span>
              <div className="flex gap-1">
                {METRICS.map((m) => (
                  <button
                    key={m.key}
                    onClick={() => setMetric(m.key)}
                    className={
                      'px-2 py-1 rounded text-[10px] border transition-colors ' +
                      (metric === m.key
                        ? 'border-brand/50 bg-brand/10 text-brand'
                        : 'border-ink-600 text-mist-400 hover:text-mist-200 hover:border-ink-500')
                    }
                  >
                    {m.label}
                  </button>
                ))}
              </div>
            </div>
            <div className="p-2">
              <IndiaMap
                districts={mapDistricts}
                stateRisk={stateRisk}
                metric={metric}
                selectedDistrict={selected}
                onSelectDistrict={(code) => setSelected(code === selected ? null : code)}
              />
            </div>
          </div>

          <div className="space-y-4">
            {/* selected district card */}
            {selectedDistrict && (
              <div className="panel">
                <div className="panel-head">
                  <span>{selectedDistrict.districtName}, {selectedDistrict.stateName}</span>
                  <button
                    onClick={() => setSelected(null)}
                    className="text-mist-400 hover:text-mist-100 text-[10px]"
                  >
                    clear
                  </button>
                </div>
                <div className="p-3 grid grid-cols-2 gap-x-4 gap-y-2 text-xs">
                  <Stat label="Facilities" value={count(selectedDistrict.facilities)} />
                  <Stat label="Positions" value={count(selectedDistrict.trackedPositions)} />
                  <Stat label="Critical" value={count(selectedDistrict.criticalPositions)} tone="critical" />
                  <Stat label="Zero stock" value={pct(selectedDistrict.zeroStockShare)} />
                  <Stat label="Mean risk" value={selectedDistrict.meanRiskScore.toFixed(1)} />
                  <Stat label="Expiring" value={inr(selectedDistrict.projectedWasteInr)} />
                  <Stat
                    label="Supply reliability"
                    value={pct(selectedDistrict.reliability, 0)}
                    hint="Modelled: how reliably consignments arrive complete and on time."
                  />
                  <Stat
                    label="Demand-driven"
                    value={pct(selectedDistrict.pullFraction, 0)}
                    hint="How far allocation follows real consumption rather than tier norms. Low values mean push allocation, which starves large facilities and overstocks small ones."
                  />
                </div>
                <div className="px-3 pb-3">
                  <Link
                    href={`/district/${selectedDistrict.districtCode}`}
                    className="block text-center text-[11px] py-1.5 rounded border border-brand/40 text-brand hover:bg-brand/10 transition-colors"
                  >
                    Open district console →
                  </Link>
                </div>
              </div>
            )}

            {/* worst districts */}
            <div className="panel">
              <div className="panel-head">
                <span>Highest-risk districts</span>
                <span className="text-mist-500 normal-case tracking-normal">
                  population-weighted
                </span>
              </div>
              <div className="divide-y divide-ink-800">
                {worstDistricts.map((d, i) => (
                  <button
                    key={d.districtCode}
                    onClick={() => setSelected(d.districtCode)}
                    className="row-hover w-full text-left px-3 py-2 flex items-center gap-3 transition-colors"
                  >
                    <span className="tnum text-[10px] text-mist-500 w-5">{i + 1}</span>
                    <span className="flex-1 min-w-0">
                      <span className="block text-xs text-mist-100 truncate">{d.districtName}</span>
                      <span className="block text-[10px] text-mist-400 truncate">{d.stateName}</span>
                    </span>
                    <span className="text-right">
                      <span className="block tnum text-xs text-mist-100">{d.meanRiskScore.toFixed(1)}</span>
                      <span className="block text-[10px] text-mist-400 tnum">
                        {count(d.criticalPositions)} crit
                      </span>
                    </span>
                  </button>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* ---------------- alerts ---------------- */}
        <section className="panel">
          <div className="panel-head">
            <span>
              Priority stock alerts
              {selected && selectedDistrict ? ` · ${selectedDistrict.districtName}` : ' · national'}
            </span>
            <span className="text-mist-500 normal-case tracking-normal">
              ranked by risk score · {count(visibleAlerts.length)} shown
            </span>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-xs">
              <thead>
                <tr className="text-[10px] uppercase tracking-wider text-mist-400 border-b border-ink-700">
                  <Th className="text-left pl-3">Facility</Th>
                  <Th className="text-left">District</Th>
                  <Th className="text-left">Drug</Th>
                  <Th>VED</Th>
                  <Th className="text-right">On hand</Th>
                  <Th className="text-right">Cover</Th>
                  <Th className="text-right">Lead</Th>
                  <Th className="text-right">P(out)</Th>
                  <Th className="text-right">Shortfall</Th>
                  <Th className="text-right pr-3">Risk</Th>
                </tr>
              </thead>
              <tbody className="divide-y divide-ink-800">
                {visibleAlerts.map((a, i) => (
                  <tr key={a.facilityId + a.drugId + i} className="row-hover transition-colors">
                    <td className="pl-3 py-1.5">
                      <span className="text-mist-100">{a.facilityName}</span>
                    </td>
                    <td className="text-mist-400">
                      {a.districtName}
                      <span className="text-mist-500"> · {a.stateName}</span>
                    </td>
                    <td className="text-mist-200">
                      {a.drugName}
                      <span className="text-mist-500"> {a.drugStrength}</span>
                    </td>
                    <td className="text-center">
                      <span
                        className={
                          'text-[10px] px-1.5 py-0.5 rounded border ' +
                          (a.ved === 'V'
                            ? 'border-sev-critical/40 text-sev-critical bg-sev-critical/10'
                            : a.ved === 'E'
                              ? 'border-sev-high/30 text-sev-high bg-sev-high/10'
                              : 'border-ink-600 text-mist-400')
                        }
                        title={VED_LABEL[a.ved]}
                      >
                        {a.ved}
                      </span>
                    </td>
                    <td className="text-right tnum">
                      {a.onHand === 0 ? (
                        <span className="text-sev-critical font-semibold">0</span>
                      ) : (
                        <span className="text-mist-200">{count(a.onHand)}</span>
                      )}
                      <span className="text-mist-500 text-[10px]"> {a.unit}</span>
                    </td>
                    <td className="text-right tnum text-mist-300">{days(a.daysOfCover)}</td>
                    <td className="text-right tnum text-mist-400">{a.leadTimeDays}d</td>
                    <td className="text-right tnum text-mist-200">
                      {(a.stockoutProbability * 100).toFixed(0)}%
                    </td>
                    <td className="text-right tnum text-mist-300">
                      {count(a.expectedShortfallUnits)}
                    </td>
                    <td className="text-right pr-3 py-1.5">
                      <span
                        className={
                          'tnum text-[11px] px-1.5 py-0.5 rounded border ' +
                          SEVERITY_CLASS[a.severity as Severity]
                        }
                      >
                        {a.riskScore}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          {visibleAlerts.length === 0 && (
            <p className="p-4 text-xs text-mist-400">No critical alerts in this district.</p>
          )}
        </section>

        {/* ---------------- provenance ---------------- */}
        <footer className="panel p-4 text-[11px] text-mist-400 leading-relaxed">
          <p className="text-mist-200 font-semibold mb-2 text-xs">What is real here, and what is not</p>
          <div className="grid md:grid-cols-2 gap-4">
            <div>
              <p className="text-sev-low mb-1">Real</p>
              <ul className="space-y-0.5 list-disc list-inside">
                <li>Districts, state LGD/Census codes, and coordinates</li>
                <li>IPHS facility tiers and catchment norms</li>
                <li>Drug catalogue, VED classification, cold-chain flags</li>
                <li>Every model, forecast and optimisation in the system</li>
              </ul>
            </div>
            <div>
              <p className="text-sev-moderate mb-1">Simulated</p>
              <ul className="space-y-0.5 list-disc list-inside">
                <li>Individual facilities, their names and catchments</li>
                <li>Stock positions, batches and consumption ledgers</li>
                <li>District supply reliability and allocation behaviour</li>
              </ul>
            </div>
          </div>
          <p className="mt-3 pt-3 border-t border-ink-800">
            Real PHC inventory data is not public. The facility layer is generated by a calibrated
            simulator so the system can be evaluated end to end; connecting a live DVDMS / e-Aushadhi
            extract replaces the simulator and changes nothing downstream. Snapshot of{' '}
            <span className="tnum text-mist-300">{count(t.trackedPositions)}</span> stock positions
            computed in <span className="tnum text-mist-300">{snapshot.buildSeconds}s</span>.
          </p>
        </footer>
      </main>
    </div>
  );
}
