/**
 * The worked outbreak scenario the README and the deck quote.
 *
 * Run with:  npx tsx scripts/surge-example.mts
 * Output:    docs/surge-example.json / .md
 *
 * WHY A SCRIPT AND NOT A PARAGRAPH
 * --------------------------------
 * The sentence this produces -- "at routine valuation N of M surge needs are
 * servable; under emergency valuation P are, for Rs X more transport" -- is the
 * single most quotable thing WS3 makes, which is exactly why it must not be
 * typed by hand. Every figure this project publishes is read from a re-run
 * script or a shipped payload, and `check-claims` fails the build when prose
 * and artefact disagree.
 *
 * The scenario is deterministic -- same district, pattern, multiplier and seed
 * -- so this is reproducible rather than a snapshot of one lucky run. The test
 * suite asserts that determinism separately.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { simulateSurge } from '../src/lib/surge/scenario';
import { asForecastCache, asForecastMethod } from '../src/lib/forecast/timesfm';

const root = process.cwd();
const read = (p: string) => readFileSync(resolve(root, p), 'utf8');

/**
 * Purnia, vector-borne, doubled.
 *
 * The same district the live-loop rehearsal and the deck's dispatch order use.
 * One district carried through every surface is worth more than five districts
 * each mentioned once: a reader who checks one of them can check all of them.
 */
const DISTRICT = process.env.AAROGYA_SURGE_DISTRICT ?? 'DST-10-PURNIA';
const PATTERN = 'monsoon_vector' as const;
const MULTIPLIER = 2;

const result = simulateSurge({
  districtCode: DISTRICT,
  pattern: PATTERN,
  multiplier: MULTIPLIER,
  forecastCache: asForecastCache(JSON.parse(read('src/data/forecast-cache.json'))),
  forecastMethod: asForecastMethod(JSON.parse(read('src/data/forecast-method.json'))),
});

const routineNeeds = result.routine.served + result.routine.unserved;
const emergencyNeeds = result.emergency.served + result.emergency.unserved;
const inr = (v: number) => '₹' + Math.round(v).toLocaleString('en-IN');

const artefact = {
  districtCode: result.districtCode,
  districtName: result.districtName,
  stateName: result.stateName,
  pattern: result.pattern,
  patternLabel: result.patternLabel,
  multiplier: result.multiplier,
  days: result.days,
  medicines: result.drugs.map((d) => d.name),
  positions: result.positions,
  criticalBefore: result.baseline.critical,
  criticalUnderSurge: result.surged.critical,
  newlyCritical: result.newlyCritical,
  routine: { ...result.routine, needs: routineNeeds },
  emergency: { ...result.emergency, needs: emergencyNeeds },
  extraNeedsServed: result.extraNeedsServed,
  extraTransportInr: result.extraTransportInr,
  /** The sentence itself, so prose and artefact cannot drift by a word. */
  sentence:
    result.routine.served + ' of ' + routineNeeds +
    ' surge needs servable at routine valuation, ' + result.emergency.served +
    ' at emergency, for ' + inr(result.extraTransportInr) + ' more transport',
  topOrders: result.orders.slice(0, 5),
  elapsedMs: result.elapsedMs,
};

writeFileSync(resolve(root, 'docs/surge-example.json'), JSON.stringify(artefact, null, 2) + '\n');

const md = [
  '# A worked outbreak scenario',
  '',
  '*Generated by `npm run surge:example`. Do not edit by hand.*',
  '',
  '**' + result.patternLabel + ', caseload ×' + result.multiplier + ' for ' + result.days +
    ' days, in ' + result.districtName + ', ' + result.stateName + '.**',
  '',
  'Only the medicines that treat it are re-scored or moved: ' +
    result.drugs.map((d) => d.name).join(', ') + '. A dengue outbreak does not raise demand for',
  'oxytocin, and restricting the scenario to the pattern\'s formulary is also what keeps it inside four',
  'seconds — this run took ' + result.elapsedMs + ' ms.',
  '',
  '| | Before | Under the outbreak |',
  '|---|---|---|',
  '| Critical positions | ' + result.baseline.critical + ' | ' + result.surged.critical +
    ' (' + result.newlyCritical + ' newly) |',
  '| Expected shortfall, units | ' + result.baseline.expectedShortfallUnits.toLocaleString('en-IN') +
    ' | ' + result.surged.expectedShortfallUnits.toLocaleString('en-IN') + ' |',
  '',
  '## The part that is a policy question, not a modelling one',
  '',
  'Raising demand alone produces a wall of refusals. That is the measured behaviour of this planner under',
  'load: an outbreak raises both sides of the benefit/cost ratio, so the gate barely moves. What changes the',
  'answer is the price of a stock-out — a ministry dial, exposed rather than baked in.',
  '',
  '| | Routine | Emergency |',
  '|---|---|---|',
  '| One averted Vital unit is worth | ' + inr(result.routine.shortagePenalty.V) + ' | ' +
    inr(result.emergency.shortagePenalty.V) + ' |',
  '| Surge needs served | ' + result.routine.served + ' of ' + routineNeeds + ' | ' +
    result.emergency.served + ' of ' + emergencyNeeds + ' |',
  '| Refused on benefit/cost | ' + result.routine.failedBenefitCost + ' | ' +
    result.emergency.failedBenefitCost + ' |',
  '| Transport | ' + inr(result.routine.transportInr) + ' | ' + inr(result.emergency.transportInr) + ' |',
  '',
  '**' + artefact.sentence + '.**',
  '',
  'Both plans are returned, always. A scenario that reported only the emergency one would be presenting a',
  'policy decision as a computation.',
  '',
  '## Pre-positioning orders the emergency plan issues',
  '',
  '| From | To | Medicine | Quantity | Distance | Transport |',
  '|---|---|---|---|---|---|',
  ...result.orders.slice(0, 5).map(
    (o) =>
      '| ' + o.fromFacilityName + (o.crossDistrict ? ' (' + o.fromDistrict + ')' : '') +
      ' | ' + o.toFacilityName + ' | ' + o.drugName + ' | ' + o.quantity + ' ' + o.unit +
      ' | ' + o.distanceKm + ' km | ' + inr(o.estimatedCostInr) + ' |',
  ),
  '',
  '_Nobody has observed this outbreak. It is a scenario, computed on demand, and every number above comes',
  'from the same risk model and the same planner the nightly build runs._',
  '',
].join('\n');

writeFileSync(resolve(root, 'docs/surge-example.md'), md);

console.log('Worked surge scenario: ' + result.districtName + ', ' + result.patternLabel);
console.log('  ' + artefact.sentence);
console.log('  critical ' + result.baseline.critical + ' -> ' + result.surged.critical +
  ' · computed in ' + result.elapsedMs + ' ms');
console.log('  wrote docs/surge-example.json and docs/surge-example.md');
